server:
  port: 8083
---
spring.cloud.stream:
  function:
    definition: processor
  bindings:
    processor-in-0:
      destination: order-created
    processor-out-0:
      destination: order-updated
---
service:
  endpoints:
    inventory: http://localhost:8081
    payment: http://localhost:8082