spring.cloud.stream:
  function:
    definition: inventoryProcessor
  bindings:
    inventoryProcessor-in-0:
      destination: order-event
    inventoryProcessor-out-0:
      destination: inventory-event