version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  publisher:
    build: ./redis-publisher
    image: vinsdocker/redis-publisher
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
  subscriber:
    build: ./redis-subscriber
    image: vinsdocker/redis-subscriber
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis